// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OtoKurSkoda.Infrastructure.Context;

#nullable disable

namespace OtoKurSkoda.Infrastructure.Migrations
{
    [DbContext(typeof(OtoKurSkodaDbContext))]
    [Migration("20251227120647_t1")]
    partial class t1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("OtoKurSkoda")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.ToTable("Roles", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.RoleGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.ToTable("RoleGroups", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.RoleGroupRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<Guid>("RoleGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.HasIndex("RoleGroupId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleGroupRoles", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PhoneConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.ToTable("Users", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.UserAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<string>("TaxNumber")
                        .HasColumnType("text");

                    b.Property<string>("TaxOffice")
                        .HasColumnType("text");

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAddresses ", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<Guid>("RoleGroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.RefreshToken", b =>
                {
                    b.HasOne("OtoKurSkoda.Domain.Entitys.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.RoleGroupRole", b =>
                {
                    b.HasOne("OtoKurSkoda.Domain.Entitys.RoleGroup", "RoleGroup")
                        .WithMany("RoleGroupRoles")
                        .HasForeignKey("RoleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OtoKurSkoda.Domain.Entitys.Role", "Role")
                        .WithMany("RoleGroupRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("RoleGroup");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.UserAddress", b =>
                {
                    b.HasOne("OtoKurSkoda.Domain.Entitys.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.UserRole", b =>
                {
                    b.HasOne("OtoKurSkoda.Domain.Entitys.RoleGroup", "RoleGroup")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OtoKurSkoda.Domain.Entitys.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoleGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.Role", b =>
                {
                    b.Navigation("RoleGroupRoles");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.RoleGroup", b =>
                {
                    b.Navigation("RoleGroupRoles");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
