// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OtoKurSkoda.Infrastructure.Context;

#nullable disable

namespace OtoKurSkoda.Infrastructure.Migrations
{
    [DbContext(typeof(OtoKurSkodaDbContext))]
    [Migration("20260101110813_AddCategoryColor")]
    partial class AddCategoryColor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("OtoKurSkoda")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.AttributeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<string>("DataType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("text");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFilterable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisibleOnProductPage")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PossibleValues")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("AttributeDefinitions", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Brands", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("IconClass")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.CategoryAttribute", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.HasKey("CategoryId", "AttributeDefinitionId");

                    b.HasIndex("AttributeDefinitionId");

                    b.ToTable("CategoryAttributes", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Manufacturers", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<string>("AdminNote")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("BillingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BillingCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BillingDistrict")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BillingFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BillingLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BillingPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("BillingPostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CargoCompany")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<string>("CustomerNote")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ShippingCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("ShippingCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ShippingDistrict")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShippingEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ShippingFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShippingLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShippingPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ShippingPostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreateTime");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("OrderStatus");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProductOemNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProductSku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal?>("DiscountedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsBestSeller")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNewArrival")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("boolean");

                    b.Property<int?>("LowStockThreshold")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OemNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SoldCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TaxRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<bool>("TrackInventory")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("OemNumber");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.ProductAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<Guid>("AttributeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AttributeDefinitionId");

                    b.HasIndex("ProductId", "AttributeDefinitionId")
                        .IsUnique();

                    b.ToTable("ProductAttributes", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.ProductCompatibility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int?>("StartYear")
                        .HasColumnType("integer");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.Property<Guid>("VehicleGenerationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VehicleGenerationId");

                    b.HasIndex("ProductId", "VehicleGenerationId")
                        .IsUnique();

                    b.ToTable("ProductCompatibilities", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<string>("AltText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.RelatedProduct", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RelatedProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("similar");

                    b.HasKey("ProductId", "RelatedProductId");

                    b.HasIndex("RelatedProductId");

                    b.ToTable("RelatedProducts", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.ToTable("Roles", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.RoleGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.ToTable("RoleGroups", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.RoleGroupRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<Guid>("RoleGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.HasIndex("RoleGroupId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleGroupRoles", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PhoneConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.ToTable("Users", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.UserAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<string>("TaxNumber")
                        .HasColumnType("text");

                    b.Property<string>("TaxOffice")
                        .HasColumnType("text");

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAddresses ", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<Guid>("RoleGroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.VehicleGeneration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.Property<Guid>("VehicleModelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VehicleModelId");

                    b.ToTable("VehicleGenerations", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.VehicleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<Guid>("TenatId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.HasIndex("BrandId", "Slug")
                        .IsUnique();

                    b.ToTable("VehicleModels", "OtoKurSkoda");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.Cart", b =>
                {
                    b.HasOne("OtoKurSkoda.Domain.Entitys.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.CartItem", b =>
                {
                    b.HasOne("OtoKurSkoda.Domain.Entitys.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OtoKurSkoda.Domain.Entitys.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.Category", b =>
                {
                    b.HasOne("OtoKurSkoda.Domain.Entitys.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.CategoryAttribute", b =>
                {
                    b.HasOne("OtoKurSkoda.Domain.Entitys.AttributeDefinition", "AttributeDefinition")
                        .WithMany("CategoryAttributes")
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OtoKurSkoda.Domain.Entitys.Category", "Category")
                        .WithMany("CategoryAttributes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDefinition");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.Order", b =>
                {
                    b.HasOne("OtoKurSkoda.Domain.Entitys.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.OrderItem", b =>
                {
                    b.HasOne("OtoKurSkoda.Domain.Entitys.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OtoKurSkoda.Domain.Entitys.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.Product", b =>
                {
                    b.HasOne("OtoKurSkoda.Domain.Entitys.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OtoKurSkoda.Domain.Entitys.Manufacturer", "Manufacturer")
                        .WithMany("Products")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.ProductAttribute", b =>
                {
                    b.HasOne("OtoKurSkoda.Domain.Entitys.AttributeDefinition", "AttributeDefinition")
                        .WithMany("ProductAttributes")
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OtoKurSkoda.Domain.Entitys.Product", "Product")
                        .WithMany("Attributes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDefinition");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.ProductCompatibility", b =>
                {
                    b.HasOne("OtoKurSkoda.Domain.Entitys.Product", "Product")
                        .WithMany("Compatibilities")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OtoKurSkoda.Domain.Entitys.VehicleGeneration", "VehicleGeneration")
                        .WithMany("CompatibleProducts")
                        .HasForeignKey("VehicleGenerationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("VehicleGeneration");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.ProductImage", b =>
                {
                    b.HasOne("OtoKurSkoda.Domain.Entitys.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.RefreshToken", b =>
                {
                    b.HasOne("OtoKurSkoda.Domain.Entitys.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.RelatedProduct", b =>
                {
                    b.HasOne("OtoKurSkoda.Domain.Entitys.Product", "Product")
                        .WithMany("RelatedProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OtoKurSkoda.Domain.Entitys.Product", "Related")
                        .WithMany("RelatedToProducts")
                        .HasForeignKey("RelatedProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Related");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.RoleGroupRole", b =>
                {
                    b.HasOne("OtoKurSkoda.Domain.Entitys.RoleGroup", "RoleGroup")
                        .WithMany("RoleGroupRoles")
                        .HasForeignKey("RoleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OtoKurSkoda.Domain.Entitys.Role", "Role")
                        .WithMany("RoleGroupRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("RoleGroup");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.UserAddress", b =>
                {
                    b.HasOne("OtoKurSkoda.Domain.Entitys.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.UserRole", b =>
                {
                    b.HasOne("OtoKurSkoda.Domain.Entitys.RoleGroup", "RoleGroup")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OtoKurSkoda.Domain.Entitys.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoleGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.VehicleGeneration", b =>
                {
                    b.HasOne("OtoKurSkoda.Domain.Entitys.VehicleModel", "VehicleModel")
                        .WithMany("Generations")
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.VehicleModel", b =>
                {
                    b.HasOne("OtoKurSkoda.Domain.Entitys.Brand", "Brand")
                        .WithMany("VehicleModels")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.AttributeDefinition", b =>
                {
                    b.Navigation("CategoryAttributes");

                    b.Navigation("ProductAttributes");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.Brand", b =>
                {
                    b.Navigation("VehicleModels");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.Category", b =>
                {
                    b.Navigation("CategoryAttributes");

                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.Manufacturer", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.Product", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Compatibilities");

                    b.Navigation("Images");

                    b.Navigation("RelatedProducts");

                    b.Navigation("RelatedToProducts");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.Role", b =>
                {
                    b.Navigation("RoleGroupRoles");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.RoleGroup", b =>
                {
                    b.Navigation("RoleGroupRoles");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.VehicleGeneration", b =>
                {
                    b.Navigation("CompatibleProducts");
                });

            modelBuilder.Entity("OtoKurSkoda.Domain.Entitys.VehicleModel", b =>
                {
                    b.Navigation("Generations");
                });
#pragma warning restore 612, 618
        }
    }
}
